// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WFCity.Data.EF;

namespace WFCity.Data.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20220516174853_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WFCity.Data.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("WFCity.Data.Entities.LoaiVe", b =>
                {
                    b.Property<int>("LoaiVeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<double>("GiaVe")
                        .HasColumnType("float");

                    b.HasKey("LoaiVeId");

                    b.ToTable("LoaiVes");
                });

            modelBuilder.Entity("WFCity.Data.Entities.MaGiamGia", b =>
                {
                    b.Property<int>("MaGiamGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLuongSuDung")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SoTien")
                        .HasColumnType("int");

                    b.Property<string>("TenMaGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TyLe")
                        .HasColumnType("int");

                    b.HasKey("MaGiamGiaId");

                    b.ToTable("MaGiamGias");
                });

            modelBuilder.Entity("WFCity.Data.Entities.ThongTinVe", b =>
                {
                    b.Property<int>("ThongTinVeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoaiVeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaGiamGiaId")
                        .HasColumnType("int");

                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBanVe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTaoVe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoDienThoai")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ThongTinVeId");

                    b.HasIndex("LoaiVeId");

                    b.HasIndex("MaGiamGiaId");

                    b.ToTable("ThongTinVes");
                });

            modelBuilder.Entity("WFCity.Data.Entities.ThongTinVe", b =>
                {
                    b.HasOne("WFCity.Data.Entities.LoaiVe", "LoaiVe")
                        .WithMany("ThongTinVes")
                        .HasForeignKey("LoaiVeId");

                    b.HasOne("WFCity.Data.Entities.MaGiamGia", "MaGiamGia")
                        .WithMany("ThongTinVes")
                        .HasForeignKey("MaGiamGiaId");

                    b.Navigation("LoaiVe");

                    b.Navigation("MaGiamGia");
                });

            modelBuilder.Entity("WFCity.Data.Entities.LoaiVe", b =>
                {
                    b.Navigation("ThongTinVes");
                });

            modelBuilder.Entity("WFCity.Data.Entities.MaGiamGia", b =>
                {
                    b.Navigation("ThongTinVes");
                });
#pragma warning restore 612, 618
        }
    }
}
